//Brian Hodge
//C00170400
//CMPS 260
//Programming Assignment: #3
//Due Date: 2/28/2019 @ 11:55pm
//Program Description: This program contains a class 'Main' and class 'greenBean'. An array of 10 elements of greenBean
//                     class type is created and assigned a unique green bean class object in the 'main' method of the
//                     class Main. 3 other methods are created in the class 'Main' that are passed an array of class
//                     'greenBean': output the green bean strain information, calculate and output the average bean pod
//                     length, and calculate and output the average number of seeds in a green bean pod.
//Certificate of Authenticity:
// I certify that the code of this project, other than that that was generated by IntelliJ, is entirely my own work.

package com.company;

public class Main {

    public static void beanInformation(greenBeans[] strain) { // oid method that when passed an array of green bean
        for (int i = 0; i < strain.length; i++) {             // class type, outputs the information about each green
            if (strain[i].getType() != null) {                // bean object referenced by the elements of the array passed to the method.
                System.out.print("Stain: " + strain[i].getType() + ", ");
                System.out.printf("Pod length: " + "%1.2f", strain[i].getPodLength());
                System.out.println(", " + "Seeds in a pod: " + strain[i].getNumOfSeeds());
            }
        }
    }

    public static double avgPodLength(greenBeans[] strain) { // method that when passed an array of green bean class type,
        double total = 0;                                    // returns the average length of the pods referenced
        double beanCount = 0;                                // by the elements in the array.
        double average = 0;

        for (int i = 0; i < strain.length; i++) {
            if (strain[i].getType() != null) {
                total = total + strain[i].getPodLength();
                beanCount = beanCount + 1;
                average = (total / beanCount);
            }
        } return average;
    }

    public static int avgNumOfSeeds(greenBeans[] strain) {  // method that when passed an array of green bean class type,
        double sum = 0;                                     // returns the average number of seeds in the pods of the
        int beanCount = 0;                                  // beans referenced by the elements in the array.
        double average = 0;

        for (int i = 0; i < strain.length; i++) {
            if (strain[i].getType() != null) {
                sum = sum + strain[i].getNumOfSeeds();
                beanCount = beanCount + 1;
                average = (sum / beanCount);
            }
        }return (int)(average);
    }

    public static void main(String[] args) {

        greenBeans[] strain = new greenBeans[10]; //an array of green bean class type, w/ 10 elements of green bean
                                                  //class type... 7 unique objects of green bean class type & 3 'null'.

        strain[0] = new greenBeans("string beans",Math.random() * 10,4);
        strain[1] = new greenBeans("filet beans", Math.random() * 10, (int)(Math.random() * 10));
        strain[2] = new greenBeans("long beans", Math.random() * 10, (int)(Math.random() * 10));
        strain[3] = new greenBeans();
        strain[4] = new greenBeans("purple string beans", Math.random() * 10, (int)(Math.random() * 10));
        strain[5] = new greenBeans("flat beans", Math.random() * 10, (int)(Math.random() * 10));
        strain[6] = new greenBeans();
        strain[7] = new greenBeans("wax beans", Math.random() * 10, (int)(Math.random() * 10));
        strain[8] = new greenBeans("bush beans", Math.random() * 10, (int)(Math.random() * 10));
        strain[9] = new greenBeans();

        beanInformation(strain); System.out.println();  //calling of beanInformation method
        System.out.print("Average Pod Length: ");
        System.out.printf("%1.2f",  avgPodLength(strain)); System.out.println(); //calling of avgPodLength method
        System.out.println();
        System.out.println("Average number of seeds in a pod: " + avgNumOfSeeds(strain)); //calling of avgNumOfSeeds
                                                                                          //method
    }
}
